### ISSUE TITLE
how to calculate x(qualicty)

### ISSUE THREAD

**Issue by hzgzh** [braamvandyk/SteamTables.jl#6]
I am using SteamTable for project,but can't find relate to x(quality) function, could you provide some function relate to quality, like phx ,sat liquid and steam enthalpy and pqh pqs

**Comment by braamvandyk** [comment]
I'll be happy to do so. Just give me a little time to get around to it.

**Comment by braamvandyk** [comment]
Right, finally have time to get to this. Now, just to clarify:

Are you looking for utility functions that return the quality, given for example P and h (Quality_Ph) or functions that take the quality as an input, for example SpecificG_Px?

**Comment by hzgzh** [comment]
right

**Comment by braamvandyk** [comment]
OK, finally. I added four quality functions. You can get the qualioty with any combination of T/P with h/s. The saturated properties where added from IAPWS SR1-86(1992). This introduced an alternative Psat correlation, of which I needed the derivative. Interestingly, even though there is next to no difference between this Psat and the one I used, the derivatives are different enough to affect the specific enthalpy of the liquid at Tc to a few decimal places. I therefore included both models and call the new one only in the saturated property methods. I'll tag a new version that will close this issue.
