### ISSUE TITLE
Copy paste issue in doctrings

### ISSUE THREAD

**Issue by jtf621** [braamvandyk/SteamTables.jl#7]
The docstrings for `SpeedOfSound_Ph` and `SpeedOfSound_Ps`  describe `Utility function that returns the speciic entropy [kJ/kgK] from P [MPa] and s [kJ/kgK].`  The `SpeedOfSound` function docstring appears to be correct.

Thanks for open sourcing this code.  I was reading through it to see if it would be useful to me and noticed the docstring issue.

**Comment by braamvandyk** [comment]
Thanks! I appreciate the heads-up. Will fix ASAP. Glad you can use the code.

**Comment by braamvandyk** [comment]
Fixed.
